### ISSUE TITLE
"ImportError: cannot import name check"

### ISSUE THREAD

**Issue by holtgrewe** [UtrechtUniversity/irods-consistency-check#12]
Hi, I followed the installation instructions on CentOS 7 using Python 2.7. However, I'm getting the following error. The problem does not occur with Python 3. It looks like the recursive import does not work and it would be better

```
(irods-consistency-check) 0|0|sodar-irods-res-2 ~ # /opt/irods-consistency-check/bin/ichk
Traceback (most recent call last):
  File "/opt/irods-consistency-check/bin/ichk", line 11, in <module>
    load_entry_point('ichk==0.3.1', 'console_scripts', 'ichk')()
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/ichk/command.py", line 8, in <module>
    from ichk import check
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/ichk/check.py", line 12, in <module>
    from ichk.formatters import Formatter
  File "/opt/irods-consistency-check/lib/python2.7/site-packages/ichk/formatters.py", line 4, in <module>
    from ichk import check
ImportError: cannot import name check
```

**Comment by holtgrewe** [comment]
Sorry, duplicate of #11.
